#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "snapShot.h"
#include "generateHtmlReport.h"
#include "resetCollection.h"
#include "Save_Load.h"
#include "Dictionary.h"
#pragma once
void menu();
